# generated by datamodel-codegen:
#   filename:  model.json
#   timestamp: 2024-03-18T20:09:34+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel

import json

def 
class CellLine(BaseModel):
    name: str
    type: str
    organism: Optional[str] = None

print(json.dumps(CellLine.model_json_schema(), indent=2))
