# generated by datamodel-codegen:
#   filename:  model.json
#   timestamp: 2024-03-18T20:09:34+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

import json

def pop_default_ui(s):
    s.pop('default')
    s.update({"ui": 
              {
                  "preview": 
                  {
                      "visible": True
                      }
                      }
                      })
class CellLine(BaseModel):
    name: str
    type: str
    organism: str = Field(default="", json_schema_extra=lambda x: x.pop("default"))

print(json.dumps(CellLine.model_json_schema(), indent=2))
